import textwrap

from advent_of_code.puzzles.year_2024 import day_08


class TestSolution:
    _PUZZLE_INPUT = day_08.parse(
        textwrap.dedent("""\
            ............
            ........0...
            .....0......
            .......0....
            ....0.......
            ......A.....
            ............
            ............
            ........A...
            .........A..
            ............
            ............
        """)
    )

    def test_part_1(self) -> None:
        assert day_08.solve_part_1(self._PUZZLE_INPUT) == 14

    def test_part_2(self) -> None:
        assert day_08.solve_part_2(self._PUZZLE_INPUT) == 34
