import textwrap

from advent_of_code.puzzles.year_2025 import day_07


class TestSolution:
    _PUZZLE_INPUT = day_07.parse(
        textwrap.dedent("""\
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
        """)
    )

    def test_part_1(self) -> None:
        assert day_07.solve_part_1(self._PUZZLE_INPUT) == 21

    def test_part_2(self) -> None:
        assert day_07.solve_part_2(self._PUZZLE_INPUT) == 40
